version: "3"
services:
  app:
    restart: always
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/:/src
    tty: true
    ports:
      - 9000:9000
    command: jupyter lab --ip=0.0.0.0 --port=9000 --allow-root --notebook-dir=/src
